language: java
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
  - oraclejdk6
before_install:
  - wget http://dl.google.com/android/android-sdk_r21-linux.tgz
  - tar -zxf android-sdk_r21-linux.tgz
  - export ANDROID_HOME=~/builds/47deg/restrung/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tools,platform-tools,android-14,android-17,android-16 --no-ui --force
